name = "cdap"
license = "Apache License 2.0"
licenselink = "https://github.com/cdapio/website/blob/develop/LICENSE"
description = ""
homepage = "https://github.com/cdapio/website"
tags = []
features = []
min_version = "0.41"

[author]
  name = ""
  homepage = ""
